### ISSUE TITLE
How to use ehdn-to-eh

### ISSUE THREAD

**Issue by hchetia** [fransje-lucas/ehdn-to-eh#2]
Hi @francesca-lucas Could you guide me on how to use ehdn-to-eh to convert a .json output from EHDN to the EH format?

Thanks
Hasna

**Comment by francesca-lucas** [comment]
Hi @hchetia, I created a ReadMe with instructions. The ehdn-to-eh uses the .tsv outputs from EHdn (not the .json ones). If you have any questions that are not covered in the readme, please let me know, I'd be happy to help!

**Comment by hchetia** [comment]
Hey @francesca-lucas thanks for the readme. 

Are there also any specific installation instructions for the program - any specific python version etc.?  And does it have any dependencies other than EH and EHDN?

**Comment by hchetia** [comment]
@francesca-lucas waiting for a response!

**Comment by francesca-lucas** [comment]
Hi @hchetia, apologies for the late reply! 
It doesn't directly depend on EHdn, it just expects the input csv to be in a specific format. 
As for (other) dependencies, it uses the Bio.Seq and pysam modules. Pysam requires a Linux or MacOS X system. I am not certain on the minimal required python version, when working with it myself I used the most recent version. 
Hope this helps!

**Comment by hchetia** [comment]
Thanks @francesca-lucas. I will close this issue for now.
